### ISSUE TITLE
Upgrade jQuery from v1.4.2 to v.1.9+

### ISSUE THREAD

**Issue by koustuvsinha** [vickychijwani/quickwiki#7]
To get hold of new jQuery plugin support, specially animations as in [jQuery UI](http://jqueryui.com/), as well as to enhance the codebase, should we consider upgrading our current jQuery version from 1.4.2 to 1.9.1 or beyond?

**Comment by vickychijwani** [comment]
Sure, let's update to the latest version. Let's just ensure it doesn't break any functionality or introduce new bugs.

**Comment by koustuvsinha** [comment]
Yes. Some of the old depreciated api's need to be handled.
One of which is `$.browser.msie` which was used to detect IE. But being a Chrome Extension, what is the use of this [code](https://github.com/vickychijwani/quickwiki/blob/master/script.js#L164-L175) ?

**Comment by vickychijwani** [comment]
There is no use. I must've copy-pasted it from StackOverflow and forgotten to remove it later :stuck_out_tongue:

Thanks for catching that!

**Comment by koustuvsinha** [comment]
:laughing: ok will remove that in the process!

**Comment by koustuvsinha** [comment]
PR in #8

**Comment by vickychijwani** [comment]
Fixed in 56d539a.
